### ISSUE TITLE
Make readMe for the project

### ISSUE THREAD

**Issue by SachinPrasanth777** [AnjanyKumarJaiswal/GreenWheels-Solution-Challenge-2k24-#1]
# Title

Make a `readMe.md` file
1)Include the names of the members
2)Include the Tech Stack
3)Explain the Project
4)Explain how our project is helpful

**Comment by AnjanyKumarJaiswal** [comment]
on it

**Comment by AnjanyKumarJaiswal** [comment]
readme file done
